feign:
  hystrix:
    enabled: true
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
cognitiveserviceKey: ad2d2255bf96499b8aae54f705e2d4bc
cognitiveserviceURL: https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=